# general settings
name: vsrTransformer_x4_reds
model_type: EDVRModel
scale: 4
num_gpu: 8   # set num_gpu: 0 for cpu mode   
manual_seed: 10 
crop: true

# network structures
network_g:
  type: vsrTransformer
  image_ch: 3
  num_feat: 64 
  num_frame: 5  
  num_extract_block: 5 
  num_reconstruct_block: 30 
  depth: 5  
  heads: 1   
  patch_size: 8  
  spynet_pretrained: '/cluster/work/cvl/videosr/pretrained_models/spynet/spynet.pth'   


# path
path:
  pretrain_network_g: experiments/pretrained_models/vsrTransformer_reds_x4/vsrTransformer_reds_x4_warmup.pth
  strict_load_g: false #true #  
  resume_state: ~
  root: /cluster/work/cvl/videosr/experiments/

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSDataset
    dataroot_gt: /cluster/work/cvl/videosr/REDS/train_sharp_with_val.lmdb 
    dataroot_lq: /cluster/work/cvl/videosr/REDS/train_sharp_bicubic_with_val.lmdb 
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    io_backend:
      type: lmdb

    all_gt: True   # False # 
    num_frame: 5   
    gt_size: 256
    interval_list: [1] 
    random_reverse: true 
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 4  
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: REDS4
    type: VideoTestDataset
    dataroot_gt: ./train_sharp
    dataroot_lq: ./train_sharp_bicubic/X4/
    meta_info_file: basicsr/data/meta_info/meta_info_REDS4_test_GT.txt
    # change to 'meta_info_REDSofficial4_test_GT' when use the official validation partition
    io_backend:
      type: disk

    cache_data: false
    num_frame: 5  
    padding: reflection_circle


# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4  
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000, 300000, 300000, 300000] 
    restart_weights: [1, 0.5, 0.5, 0.5] 
    eta_min: !!float 1e-7 
  
  reset_periods: true 

  total_iter: 1200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

